# Generated by Django 3.2.7 on 2023-04-01 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign_up', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='entity_id',
            field=models.UUIDField(default=1),
            preserve_default=False,
        ),
    ]
