# Generated by Django 3.2.7 on 2023-04-01 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign_up', '0002_usermodel_entity_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='entity_id',
            field=models.UUIDField(default=None),
        ),
    ]
