# Generated by Django 3.2.7 on 2023-04-02 09:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EntityAddressModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('entity_id', models.UUIDField()),
                ('address1', models.CharField(max_length=245)),
                ('address2', models.CharField(blank=True, max_length=245)),
                ('address3', models.CharField(blank=True, max_length=245)),
                ('country_id', models.IntegerField()),
                ('state_id', models.IntegerField()),
                ('city_id', models.IntegerField()),
                ('is_default', models.BooleanField(default=True)),
                ('pin_code', models.CharField(max_length=10)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
