# Generated by Django 3.2.7 on 2023-02-07 03:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToolsModel',
            fields=[
                ('tool_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('tool_name', models.CharField(max_length=128)),
                ('display_name', models.CharField(default='', max_length=128)),
                ('description', models.CharField(default='', max_length=1024)),
                ('logo', models.CharField(default='', max_length=1024)),
                ('is_active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tools',
            },
        ),
    ]
